// EXTERNAL-JAVASCRIPT-HOME

// String Shortcut "innerHTML"
document.getElementById("tag7").innerHTML="This Line is generated by Direct Script";
function tag8(){
		document.getElementById("tag8").innerHTML="This Line is generated by Direct Script (Button Type)"};
function tag9(){
		document.getElementById("tag9").innerHTML="You Clicked the below Button"};